#!/usr/bin/env bash

REQ_ROOT=~/.requests/req-TIMESTAMP-USER_upstream-master
export PYTHONPATH=~/repositories/pyperformance

python3.9 -m pyperformance compile \
    --venv $REQ_ROOT/.run/venv \
    $REQ_ROOT/compile.ini \
    master \
    > $REQ_ROOT/run.log
