name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest==7.1.3
          python -m pip install pyperf==2.4.1
      - name: Adding dummy git user
        run: |
          git config --global user.email "test@example.com"
          git config --global user.name "Test User (used in CI -- we should never have commits from this user)"
      - name: Run tests
        run: |
          python -m pytest PORTAL/tests
